---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cache.swxfll.com
  resources:
  - swxflls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.swxfll.com
  resources:
  - swxflls/finalizers
  verbs:
  - update
- apiGroups:
  - cache.swxfll.com
  resources:
  - swxflls/status
  verbs:
  - get
  - patch
  - update
